export default [
  '*[tabindex]',
  'a[href]:not([hidden])',
  'area[href]:not([hidden])',
  'button:not(:disabled):not([hidden])',
  'embed:not([hidden])',
  'iframe:not([hidden])',
  'audio[controls]:not([hidden])',
  'video[controls]:not([hidden])',
  'input:not([type="hidden"]):not(:disabled):not([hidden])',
  'object:not([hidden])',
  'select:not(:disabled):not([hidden])',
  'textarea:not(:disabled):not([hidden])',
  '*[contenteditable]:not([contenteditable="false"]):not([hidden])',
] as const
